baseURL = "https://isavedtheworldtoday.github.io/"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]
languageCode = "en-us"
theme = "hugo-smpl-theme"
title = "i saved the World today"
[params]
description = "It’s not necessary to set an agenda or raise funds to save the World. Simply make a small, considered choice, today."
name = "i saved the World today"
[params.background.fade]
enable = true
speed = 500
[params.header]
enable = true
title = "i saved the<br>World today."
[params.logo]
alt = "isavedtheworld.today"
enable = true
image = "assets/img/logo.png"
width = "100"
[params.quote]
enable = true
text = "It’s not necessary to set an agenda or raise funds to save the World. Simply make a small, considered choice, today."
[params.social_icons]
enable = true
[[params.social]]
icon = "fa-pinterest"
link = "https://www.pinterest.co.uk/isavedtheworldtoday/"
title = "Pinterest"
[[params.social]]
icon = "fa-twitter"
link = "http://twitter.com/BlackTie_co"
title = "Twitter"
[[params.social]]
icon = "fa-facebook"
link = "https://wrapbootstrap.com/user/Basicoh"
title = "Facebook"
[[params.social]]
icon = "fa-instagram"
link = "http://BlackTie.co"
title = "Instagram"
[[params.social]]
icon = "fa-envelope"
link = "mailto:admin@isavedtheworld.today"
title = "Email Me"
